# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "typst-quic-style"
version = "0.0.1"
compiler = "0.12.0"
entrypoint = "src/lib.typ"
authors = ["taniiicom"]
license = "Unlicense"
description = "This is a typst template for creating papers in the Taniii style. Forked from https://github.com/JamesxX/graceful-genetics; Thanks for the original work."
homepage = ""
repository = "https://github.com/taniiicom/typst-quic-style"
keywords = ["paper", "article", "journal", "conference"]
categories = ["paper"]
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
	"thumbnails",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnails/1.png"
